version: '3.8'
services:
  porpcorn-time-ui:
    build: ./popcorn-time-ui
    container_name: porpcorn-time-ui
    ports:
      - 3000:3000
    stdin_open: true

  nginx:
    container_name: core_popcorn-time-api
    restart: on-failure
    image: nginx:stable
    volumes:
      - ./popcorn-time-api/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/popcorn_api/staticfiles
    ports:
      - 80:80
    depends_on:
      - popcorn-time-api

  popcorn-time-api:
    container_name: porpcorn-time-api
    depends_on:
      - popcorn-time-db
    build: ./popcorn-time-api
    volumes:
      - static_volume:/app/popcorn_api/staticfiles
      - media_volume:/app/popcorn_api/mediafiles
    ports:
      - 4001:4001

  popcorn-time-db:
    container_name: porpcorn-time-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popcorn_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
  static_volume:
  media_volume: