# Generated by Django 4.0.4 on 2022-04-19 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.SmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(4)]
            ),
        ),
    ]
