# Generated by Django 4.0.4 on 2022-04-20 22:21

import movies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="plot",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.SmallIntegerField(
                validators=[movies.validators.nonsense_year_validator]
            ),
        ),
    ]
