# Generated by Django 4.0.4 on 2022-04-25 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
